name: Deploy

env:
  FAL_HOST: ${{ secrets.FAL_HOST }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    # branches:
    #   - main

jobs:

  setup-fal-serverless:
    runs-on: ubuntu-latest
    name: Setup fal-serverless

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fal-serverless

    - name: Deploy fal-serverless functions
      env:
        FAL_KEY_ID: ${{ secrets.FAL_KEY_ID }}
        FAL_KEY_SECRET: ${{ secrets.FAL_KEY_SECRET }}
      run: |
        fal-serverless function serve ./serverless/app.py make_masks --alias edit_anything_make_masks
        fal-serverless function serve ./serverless/app.py edit_image --alias edit_anything_edit_image

  deploy-app:
    runs-on: ubuntu-latest
    name: Deploy to Vercel
    needs: setup-fal-serverless

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Node dependencies
        run: |
          npm ci

      - name: Install Vercel CLI
        run: |
          npm install -g vercel@latest

      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build project
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy project to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
